import type { RenderState } from '../ui/stores/renderStore';

/**
 * The declarative mathematical properties of the fractal viewport.
 * When any of these properties change, the temporal FSM must be invalidated.
 */
export interface MathContext {
  zr: number;
  zi: number;
  cr: number;
  ci: number;
  zoom: number;
  computeMaxIter: number; // The interactive/effective max iteration cap
  paletteMaxIter: number; // The target static max iteration cap (used for consistent palette mapping)
  sliceAngle: number;
  exponent: number;
  refOrbits: Float64Array | null;
  skipIter: number;
  debugViewMode: number;
}

/**
 * The imperative execution instructions generated by the Temporal FSM for the active frame.
 */
export interface ExecutionCommand {
  /** 1.0 = full native resolution (STATIC). <1.0 = DRS sub-rect (INTERACT). */
  renderScale: number;

  /** Max step executions to compute in this frame slice (clamped by IterationBudgetController) */
  stepLimit: number;
  /** 1.0 = load struct from checkpoint; 0.0 = clear & start fresh. (Always 1.0 after cycle 1 starts) */
  loadCheckpoint: boolean;
  /** If true, flip the ping-pong buffer before running the math pass (only once per cycle). */
  advancePingPong: boolean;
  /** If true, clear the checkpoint buffer before running the math pass (only once per cycle start). */
  clearCheckpoint: boolean;

  /**
   * Blend weight for ping-pong temporal accumulation in the shader:
   *   - 0.0  → replace prev buffer entirely (first cycle, or any INTERACT frame)
   *   - 1/N  → blend: mix(prev, current, 1/N) for the Nth accumulated cycle
   * Only applied if this pass finalizes the geometry accumulation frame.
   */
  blendWeight: number;

  /** Sub-pixel jitter offsets in UV space. 0.0 when blendWeight == 0. */
  jitterX: number;
  jitterY: number;
}

/**
 * The unified contract passed down to the active render target WebGPU pass pipeline.
 */
export interface RenderFrameDescriptor {
  context: MathContext;
  command: ExecutionCommand;
  theme: RenderState;
}
